<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8d772a180f6f533b31dc740e9b40524d
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TelegramBot\\Api\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TelegramBot\\Api\\' => 
        array (
            0 => __DIR__ . '/..' . '/telegram-bot/api/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8d772a180f6f533b31dc740e9b40524d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8d772a180f6f533b31dc740e9b40524d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8d772a180f6f533b31dc740e9b40524d::$classMap;

        }, null, ClassLoader::class);
    }
}
