<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticIniteef7d19e1ab9eb8328682405d3809bd8
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TelegramBot\\Api\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TelegramBot\\Api\\' => 
        array (
            0 => __DIR__ . '/..' . '/telegram-bot/api/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticIniteef7d19e1ab9eb8328682405d3809bd8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticIniteef7d19e1ab9eb8328682405d3809bd8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticIniteef7d19e1ab9eb8328682405d3809bd8::$classMap;

        }, null, ClassLoader::class);
    }
}
