<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '57a3140dcc5ca7aa4a606a0161512fcad743bd95',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '57a3140dcc5ca7aa4a606a0161512fcad743bd95',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'heroku/heroku-buildpack-php' => array(
            'pretty_version' => 'v227',
            'version' => '227.0.0.0',
            'reference' => '29337531e7db820ba6f4d45a9d6521f60b8c27d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../heroku/heroku-buildpack-php',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'telegram-bot/api' => array(
            'pretty_version' => 'v2.3.24',
            'version' => '2.3.24.0',
            'reference' => '579f64d0ffe7f21d1f61cb8734e297686b286bf7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../telegram-bot/api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
